---
title: "Sensitivity 4"
author: "S. Pinto"
date: "December 2022"
output:
  github_document: default
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages

```{r Load packages 1, echo=TRUE, message=FALSE}
library( dplyr )
library( magrittr )
library( knitr )
library( tidyverse )
library( reshape2 )
```

```{r Load packages 2, echo=TRUE, message=FALSE, warning=FALSE}
library( phyloseq )
library( microbiome )
library( devtools )
library( stringr )
```

```{r Load packages 3, echo=TRUE, message=FALSE, warning=FALSE}
library( aod )
library( nlme )
library( lme4 )
library( splines )
library( jtools )
```

## Load the data

Here we use the relative abundance dataset.

```{r Load Data, echo=FALSE}
physeq_mOTU <- readRDS( "/Volumes/My Passport for Mac/FECBUD studie/FECBUD GitHub/Data/FECBUD_physeq_filt_relativeabundances.rds" )

# Remove patients 109 and 117 because they have too many missing timepoints
physeq_mOTU.new = subset_samples( physeq_mOTU, subject_id != "109" &  subject_id != "117" )
physeq_mOTU <- physeq_mOTU.new
```

## Select 'average' donor mOTUs

```{r donor species, echo=TRUE}
donor_A_phyloseq <- subset_samples( physeq_mOTU, subject_id == "Donor A" )
donor_A_phyloseq

## Now determine the actual 'core' or persistent species per donor
donor_A_core_species <- core_members(
  x = donor_A_phyloseq,
  detection = 0.001, # detection limit is the same as the general limit (0.1%)
  prevalence = 6 / ( length( sample_names( donor_A_phyloseq ))),
  include.lowest = TRUE
  # select only bacteria that occur at at least 2 different timepoints
)

donor_B_phyloseq <- subset_samples( physeq_mOTU, subject_id == "Donor B" )
donor_B_phyloseq

donor_B_core_species <- core_members(
  x =  donor_B_phyloseq,
  detection = 0.001, # detection limit is the same as the general limit (0.1%)
  prevalence = 6 / ( length( sample_names( donor_B_phyloseq ))),
  include.lowest = TRUE
  # select only bacteria that occur at at least 2 different timepoints
)
```

## Select patient mOTUs per timepoint 

```{r mOTUs per patient, echo=TRUE}
# Collect data for patients per timepoint
# and convert to dataframe for easier processing
baseline_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Baseline" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
baseline_bacteria.select <- select( baseline_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
baseline_per_recipient <- unstack(baseline_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Pre_FMT_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Pre-FMT" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Pre_FMT_bacteria.select <- select( Pre_FMT_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Pre_FMT_per_recipient <- unstack( Pre_FMT_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Post_1_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Post-1" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Post_1_bacteria.select <- select( Post_1_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Post_1_per_recipient <- unstack( Post_1_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Post_2_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Post-2" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Post_2_bacteria.select <- select( Post_2_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Post_2_per_recipient <- unstack( Post_2_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Post_3_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Post-3" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Post_3_bacteria.select <- select( Post_3_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Post_3_per_recipient <- unstack( Post_3_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Post_4_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Post-4" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Post_4_bacteria.select <- select( Post_4_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Post_4_per_recipient <- unstack( Post_4_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Week8_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Week8" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Week8_bacteria.select <- select( Week8_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Week8_per_recipient <- unstack( Week8_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Week10_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Week10" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Week10_bacteria.select <- select( Week10_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Week10_per_recipient <- unstack( Week10_bacteria.select[ ,1:2 ])

# Collect data for patients per timepoint
# and convert to dataframe for easier processing
Week14_bacteria <- psmelt( physeq_mOTU ) %>%
  filter( timepoint.new == "Week14" ) %>%
  filter( Abundance > 0 ) %>%
  arrange( subject_id )

# Now list all species present in each patient before FMT
Week14_bacteria.select <- select( Week14_bacteria, OTU, subject_id, treated_with_donor )
# Make a list per recipient
Week14_per_recipient <- unstack( Week14_bacteria.select[ ,1:2 ])
```

## Obtain results per patient per sample

```{r Remove donors, echo=TRUE}
# Remove donors
physeq_mOTU = subset_samples( physeq_mOTU, subject_id != "Donor A" )
physeq_mOTU = subset_samples( physeq_mOTU, subject_id != "Donor B" )
```

```{r Obtain information, echo=TRUE}
sub.id <- physeq_mOTU@sam_data[[ "subject_id" ]] %>% unique()
mOTUs.all <- physeq_mOTU@otu_table %>% rownames()
times <- physeq_mOTU@sam_data[[ "timepoint.new" ]] %>% unique()
```

```{r Dataframe with all mOTUs, echo=TRUE}
data.recipient <- matrix( nrow = length( mOTUs.all ), ncol = 11 )  
colnames( data.recipient ) <- c( "mOTUs", "Donor", "Baseline" ,"Pre_FMT", "Post_1", "Post_2", "Post_3",
                          "Post_4", "Week8", "Week10", "Week14" )
data.recipient[ ,1 ] <- mOTUs.all 
head( data.recipient )
```

```{r Loop through all patients, echo=TRUE}
custom_min <- function(x) {if (length(x)>0) min(x) else 0}
custom_max <- function(x) {if (length(x)>0) max(x) else 0}

# The list to store the results
listofresults <- list()

for( i in 1:length( physeq_mOTU@sam_data[[ "subject_id" ]] %>% unique())){
  patient = sub.id[[ i ]]
  patient.characteristics <- physeq_mOTU@sam_data[ paste( patient, "-FMT1", sep = "" )] %>% as.matrix()
  
  # select donor bacteria
  if( patient.characteristics[ ,"treated_with_donor" ] == "Donor A" ){
  Donor = donor_A_core_species
  } else if( patient.characteristics[ ,"treated_with_donor" ] == "Donor B" ) {
  Donor = donor_B_core_species }
  
  # select patient characteristics of interest
  patient.characteristics <- paste( patient.characteristics[ ,"subject_id" ] %>% as.character(), "-" , patient.characteristics[ ,"clinical_outcome_wk14" ] %>%
                                     as.character(), "-", patient.characteristics[ ,"treated_with_donor" ] %>% as.character(), "-",
                                   patient.characteristics[ ,"pretreatment" ] %>% as.character(), "-", patient.characteristics[ ,"age" ] %>% as.character(), "-",
                                   patient.characteristics[ ,"sex" ] %>% as.character())

  # mOTUs present/absent data
  for( j in 1:nrow( data.recipient )) {
    data.recipient[ j, 2 ] <- ifelse( data.recipient[ j, 1 ] %in% Donor, 1, 0)
    
    data.recipient[ j, 3 ] <- ifelse( data.recipient[ j, 1 ] %in% baseline_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 4 ] <- ifelse( data.recipient[ j, 1 ] %in% Pre_FMT_per_recipient[[ patient ]], 1, 0 )
  
    data.recipient[ j, 5 ] <- ifelse( data.recipient[ j, 1 ] %in% Post_1_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 6 ] <- ifelse( data.recipient[ j, 1 ] %in% Post_2_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 7 ] <- ifelse( data.recipient[ j, 1 ] %in% Post_3_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 8 ] <- ifelse( data.recipient[ j, 1 ] %in% Post_4_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 9 ] <- ifelse( data.recipient[ j, 1 ] %in% Week8_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 10 ] <- ifelse( data.recipient[ j, 1 ] %in% Week10_per_recipient[[ patient ]], 1, 0 )
    data.recipient[ j, 11 ] <- ifelse( data.recipient[ j, 1 ] %in% Week14_per_recipient[[ patient ]], 1, 0 )
    }
  
  data.recipient.sel <- data.recipient[apply(data.recipient[ ,-1 ], 1, function(x) !all( x == 0 )),] %>% as.data.frame()
  data.recipient.sel %>% head()
  data.recipient.sel[ ,2:11 ] <- sapply(data.recipient.sel[ ,2:11 ],as.numeric )
  data.recipient.sel[ ,2:11 ] %>% colSums()
  # some patients have missing data (colsums = NA)
  data.recipient.sel[ ,2:11 ][ data.recipient.sel[ , 2:11 ] %>% colSums() == 0 ] <- NA
  data.recipient.sel %>% head()
  
  # Possible combinations
  expand.grid( rep( list( 0:1 ), 3 ))
  expand.grid( rep( list( 0:1 ), 4 ))
  expand.grid( rep( list( 0:1 ), 7 ))
  
  data.recipient.results <- matrix( ncol = ncol( data.recipient ), nrow = nrow( data.recipient.sel ))
  colnames( data.recipient.results ) <- colnames( data.recipient )
  data.recipient.results <- data.recipient.results %>% as.data.frame()
  data.recipient.results[ ,"mOTUs" ] <- data.recipient.sel[ ,"mOTUs" ]
  data.recipient.results %>% head()
  
  for( j in 1:nrow( data.recipient.results )) {
    for (k in 5:ncol( data.recipient.results )) {
    data.recipient.results[ j, k ] <- 
      # If the pre FMT samples or the current sample is missing, name 'NA'
      if( ( is.na( data.recipient.sel[ j, 3 ]) & is.na( data.recipient.sel[ j, 4 ]) ) | is.na( data.recipient.sel[ j, k ]) ) {
        NA
        # If present at Pre-FMT, present at the current sample and been present till now (1x 0 possible), name Resident
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) != 0 &
                 data.recipient.sel[ j, k ] == 1 & 
                 sum( data.recipient.sel[ j, 5:11 ], na.rm = TRUE ) >= length(data.recipient.sel[ j, 5:11 ])) {
        "Resident"
        # If present at Pre-FMT, present at the current sample and have not always been present till now, name host transient
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) != 0 &
                 data.recipient.sel[ j, k ] == 1 & 
                 sum( data.recipient.sel[ j, 5:11 ], na.rm = TRUE ) < length(data.recipient.sel[ j, 5:11 ]) ) {
        "Host Transient"
        # If present at donor (not pre-fmt), present at the current sample and have been present since first 1 (1x 0 possible), name colonisation
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 1 & 
                 data.recipient.sel[ j, k ] == 1 & 
                 (sum( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))], na.rm = TRUE ) >= length( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))])  )) {
        "Colonisation" 
        # If present at donor (not pre-fmt), present at the current sample and have not been present since first 1 (1x 0 possible), name donor transient
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 1 & 
                 data.recipient.sel[ j, k ] == 1 & 
                 (sum( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))], na.rm = TRUE ) < length( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))])  ) ) {
       "Donor Transient"
      # If not present at pre-fmt or donor, but current present and have been present since first 1 (1x 0 possible), name Novel
        } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 0 & 
                 data.recipient.sel[ j, k ] == 1 & 
                 (sum( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))], na.rm = TRUE ) >= length( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))]) )) {
       "Novel"
          # If not present at pre-fmt or donor,  and have not been present since first 1 (1x 0 possible), name Novel transient
        } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 0 & 
                 data.recipient.sel[ j, k ] == 1 &
                 (sum( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:11 ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))], na.rm = TRUE ) < length( data.recipient.sel[ j, 5:11 ][ custom_min( which( data.recipient.sel[ j, 5:k ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:11 ] == c(0,1) ))])  ) ) {
       "Novel Transient"
# ************************************************************          
        # # the first 0 after the start of 1 is NA
        #   } else if( 
        #          data.recipient.sel[ j, k ] == 0 &
        #          
        #          ( data.recipient.sel[ j, ( k - 1 ) ] == 1 &&
        #          !is.na( data.recipient.sel[ j, ( k - 1 ) ] )) &
        #          
        #          ( (data.recipient.sel[ j, ( k + 1 ) ] == 1 &&
        #            !is.na( data.recipient.sel[ j, ( k + 1 ) ] )) ||
        #             k == 11 ) &
        #          
        #          (sum( data.recipient.sel[ j, 5:(k-1) ][ custom_min( which( data.recipient.sel[ j, 5:(k-1) ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:(k-1) ] != 0 ))], na.rm = TRUE ) >= length( data.recipient.sel[ j, 5:(k-1) ][ custom_min( which( data.recipient.sel[ j, 5:(k-1) ] != 0 )) : custom_max( which( data.recipient.sel[ j, 5:(k-1) ] != 0 ))]) )) {
        # NA
        # 
            # till presence and absent in donor an pre FMT, name absent
          } else if( 
            sum( data.recipient.sel[ j, 2:k ], na.rm = TRUE ) == 0 &
                       data.recipient.sel[ j, k ] == 0 ) {
        "Absent" 
            # if present in pre FMT samples, but not present in the current sample (except the first one), name Species loss
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) != 0 &
                 data.recipient.sel[ j, k ] == 0 ) {
        "Species loss" 
    # if present in donor sample, but not present in the current sample (except the first one), name Rejection
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 1 & 
                 data.recipient.sel[ j, k ] == 0 ) {
        "Rejection" 
      # if not present in pre-FMT or donor samples, not present currently, but have been present before as novel, novel loss
      } else if( sum( data.recipient.sel[ j, 3:4 ], na.rm = TRUE ) == 0 &
                 data.recipient.sel[ j, 2 ] == 0 & 
                 data.recipient.sel[ j, k ] == 0 ) {
       "Novel loss"
        # if not been classified according to the rules above
      } else {
        "Unclassified" 
      }
    }
  }
  data.recipient.results.meta <- cbind( data.recipient.results, patient.characteristics )
  listofresults[[ i ]]  <- data.recipient.results.meta

  # print( i )
  }
  
head( listofresults[[ i ]], 25)
```

```{r Make the count dataset, echo=TRUE, message=FALSE, warning=FALSE}
# count data
resultscounts <- list()
for(i in 1:length( listofresults )){
  resultscounts[[ i ]] <- listofresults[[ i ]] %>% 
    pivot_longer( cols = c( Donor, Baseline, Pre_FMT, Post_1, Post_2, Post_3,
                          Post_4, Week8, Week10, Week14 ), names_to = "timepoint", values_to = "category" ) %>% 
    group_by( timepoint ) %>% 
    mutate( category = factor( category, levels = c( "Resident", "Host Transient", "Species loss", 
                                                     "Colonisation", "Donor Transient", "Rejection",
                                                     "Novel", "Novel Transient", "Novel loss",
                                                     "Absent" ))) %>% 
    filter( category != "Absent" ) %>%
    summarise( n = c(( table( category )))) %>% 
    mutate( category = c( "Resident", "Host Transient", "Species loss", 
                                                     "Colonisation", "Donor Transient", "Rejection",
                                                     "Novel", "Novel Transient", "Novel loss",
                                                     "Absent" )) 
  
  resultscounts[[ i ]]$timepoint = factor( resultscounts[[ i ]]$timepoint, levels = c(  "Donor", "Baseline", "Pre_FMT","Post_1", "Post_2", "Post_3",
                                                        "Post_4", "Week8", "Week10", "Week14" ))
  resultscounts[[ i ]]$patient.characteristics <- listofresults[[ i ]]$patient.characteristics %>% unique()
  resultscounts[[ i ]][c( 'Patient_ID', 'State', 'Donor', 'Pretreatment', 'Age', 'Sex' )] <- str_split_fixed(resultscounts[[ i ]]$patient.characteristics, ' - ', 6)
  resultscounts[[ i ]] <- resultscounts[[ i ]][ c( 'Patient_ID', 'State', 'Donor', 'Pretreatment', 'Age', 'Sex' ,'timepoint', 'category', 'n' )]
}
```

```{r Unlist, echo=TRUE}
results.all.count <- bind_rows( resultscounts, .id = "column_label" )
results.all.count <- results.all.count[ c( 2:10 )]
```

## Save results

```{r Save phyloseq, eval=FALSE}
save( results.all.count, file = "Scenario3_sens.Rda" )
```

## Investigate results

```{r Investigate results, echo=TRUE}
dim( results.all.count )
head( results.all.count )
typeof( results.all.count )
hist( results.all.count$n, n = 50 )
results.all.count$timepoint %>% unique()
results.all.count$category %>% unique()
```
